import { ReservationTrigger } from "@/components/reservations/reservation-trigger";
import { Actions, ButtonLink, Eyebrow, MediaFrame, SectionHeading } from "@/components/ui";
import { createPageMetadata } from "@/lib/seo";

export const metadata = createPageMetadata({title: "Our Story", description: "Discover the Lowcountry ingredients, live-fire cooking, and warm hospitality behind Marsh & Ember.", path: "/our-story", image: "/images/story-landscape-image.jpg", imageAlt: "The Lowcountry landscape surrounding Charleston"});

export default function OurStoryPage() {
  return <>
    <section className="section story-hero"><div className="section__inner"><div className="story-copy-row"><div><Eyebrow>Our Story</Eyebrow><h1>A Charleston table, shaped by the Lowcountry.</h1></div><p className="lede">Marsh & Ember began with a simple idea: let the ingredients, seasons, and people of the Lowcountry lead. Our kitchen brings that sense of place to the table through live-fire cooking, thoughtful sourcing, and hospitality that feels generous rather than formal.</p></div><MediaFrame src="/images/story-landscape-image.jpg" mobileSrc="/images/story-mobile-landscape.jpg" alt="The Lowcountry landscape surrounding Charleston" className="media-frame--wide" priority /></div></section>

    <section className="section section--sand"><div className="split-section split-section--mobile-copy-first"><MediaFrame src="/images/story-marsh-golden-hour-image.jpg" mobileSrc="/images/story-mobile-marsh.jpg" alt="Lowcountry marsh at golden hour" /><div className="split-section__copy"><SectionHeading eyebrow="Grounded in place" title="Rooted in the Lowcountry" /><p className="lede">The Lowcountry is defined by water, fertile ground, changing seasons, and generations of food knowledge. Our menus begin there—with seafood from nearby waters, regional produce, heritage grains, and relationships built with the people who grow, harvest, and land what we cook.</p><blockquote className="editorial-quote">“We begin with what the season gives us.”</blockquote></div></div></section>

    <section className="section"><div className="section__inner"><div className="story-section-intro"><div><SectionHeading eyebrow="Culinary element" title="Drawn toward the hearth" /><p className="lede">Fire is not simply a technique in our kitchen. It creates contrast, draws out sweetness, and brings ingredients into sharper focus. Some dishes meet the flame directly; others carry its influence through smoke, embers, or a slowly built broth.</p></div><ButtonLink href="/menus" variant="secondary">Explore the Menus</ButtonLink></div><div className="story-wide-media"><MediaFrame src="/images/story-chef-and-hearth-image.jpg" mobileSrc="/images/story-mobile-hearth.jpg" alt="A chef cooking over the hearth" className="media-frame--wide" /><MediaFrame src="/images/story-chef-and-hearth-image.jpg" mobileSrc="/images/story-mobile-food.jpg" alt="A plated dish shaped by the hearth" className="media-frame--wide mobile-only" /></div></div></section>

    <section className="section section--sand story-team"><div className="section__inner"><SectionHeading eyebrow="The Team" title="The people behind the table" intro="Marsh & Ember brings together cooks, growers, makers, and hospitality professionals who believe the details of an evening matter." centered /><div className="card-grid card-grid--2 team-grid"><article className="editorial-card"><MediaFrame src="/images/story-camille-portrait.jpg" mobileSrc="/images/story-mobile-camille.jpg" alt="Camille Rivers, Executive Chef" /><div className="editorial-card__body"><h3>Camille Rivers</h3><p className="meta">Executive Chef</p><p>Camille&apos;s cooking is guided by seasonality, live fire, and a deep curiosity about the ingredients and foodways of the coastal South.</p></div></article><article className="editorial-card"><MediaFrame src="/images/story-julian-portrait.jpg" mobileSrc="/images/story-mobile-julian.jpg" alt="Julian Hart, Hospitality Director" /><div className="editorial-card__body"><h3>Julian Hart</h3><p className="meta">Hospitality Director</p><p>Julian leads the dining room with an approach centered on warmth, attentiveness, and making every guest feel genuinely welcomed.</p></div></article></div></div></section>

    <section className="section"><div className="section__inner"><div className="story-copy-row"><SectionHeading eyebrow="The experience" title="Hospitality without ceremony" /><div><p className="lede">We believe a memorable evening can feel considered without feeling formal. The welcome should be warm, the room should invite conversation, and the details should support the experience without calling attention to themselves.</p><p className="editorial-quote">Polished in the details. Easy in the experience.</p></div></div><MediaFrame src="/images/story-inhabited-dining-room-image.jpg" mobileSrc="/images/story-mobile-dining-room.jpg" alt="Guests enjoying the Marsh and Ember dining room" className="media-frame--wide" /></div></section>

    <section className="section section--sand"><div className="split-section split-section--reverse split-section--mobile-copy-first"><MediaFrame src="/images/story-ingredient-detail-image.jpg" mobileSrc="/images/story-mobile-ingredients.jpg" alt="Seasonal ingredients selected for the menu" /><div className="split-section__copy"><SectionHeading eyebrow="Thoughtful Sourcing" title="Relationships before labels" /><p className="lede">Our sourcing changes with the season and with availability. We prioritize thoughtful relationships, responsible purchasing, and ingredients that make sense for the place and moment.</p></div></div></section>

    <section className="section section--sand"><div className="section__inner"><SectionHeading title="Experience Marsh & Ember" intro="Discover the menus, plan your visit, or reserve a table for an evening shaped by the Lowcountry." centered /><Actions centered><ReservationTrigger>Reserve a Table</ReservationTrigger><ButtonLink href="/menus" variant="secondary">View Menus</ButtonLink><ButtonLink href="/visit" variant="secondary">Plan Your Visit</ButtonLink></Actions></div></section>
  </>;
}
