import type { Metadata } from "next";
import Link from "next/link";
import { Actions, ButtonLink, Eyebrow, MediaFrame, MenuItem, SectionHeading } from "@/components/ui";
import { dietaryMarkers, dinnerSections } from "@/lib/site-data";

export const metadata: Metadata = { title: "Dinner Menu", description: "Seasonal Lowcountry cooking shaped by the hearth, nearby waters, and ingredients at their best." };

export default function DinnerPage() {
  return <>
    <section className="hero hero--mobile-image-first"><div className="hero__content"><Link className="button button--text" href="/menus">← Back to All Menus</Link><Eyebrow>Menus</Eyebrow><h1>Dinner</h1><p className="lede">Seasonal Lowcountry cooking shaped by the hearth, nearby waters, and ingredients at their best.</p><p><strong>Availability</strong><br />Tuesday–Sunday · 5–10 PM</p><p className="meta">Offerings and prices change with availability.</p></div><MediaFrame src="/images/dinner-hero-dinner-image.jpg" mobileSrc="/images/dinner-mobile-hero.jpg" alt="Dinner dishes served at Marsh and Ember" priority /></section>
    <nav className="menu-switcher" aria-label="Menu selection"><Link href="/menus/dinner" aria-current="page">Dinner</Link><Link href="/menus#brunch">Weekend Brunch</Link><Link href="/menus#spirits">Cocktails &amp; Spirits</Link><Link href="/menus#cellar">Wine</Link></nav>
    <section className="section"><div className="section__inner menu-detail"><nav className="local-nav" aria-label="Dinner sections"><h2>Jump to section</h2>{dinnerSections.map((section) => <a key={section.id} href={`#${section.id}`}>{section.title}</a>)}</nav><div className="menu-sections">{dinnerSections.map((section) => <section className="menu-section" id={section.id} key={section.id}><h2>{section.title}</h2><div className="menu-section__items">{section.items.map((item) => <MenuItem item={item} key={item.name} />)}</div>{section.id === "vegetables" ? <MediaFrame src="/images/dinner-vegetables-image.jpg" mobileSrc="/images/dinner-mobile-vegetables.jpg" alt="Seasonal vegetables from Lowcountry farms" className="media-frame--wide" /> : null}{section.id === "hearth" ? <><MediaFrame src="/images/dinner-hearth-image.jpg" mobileSrc="/images/dinner-mobile-hearth.jpg" alt="Cooking directly over the hearth" className="media-frame--wide" /><p className="meta">* MP — Market Price based on seasonal day-boat availability.</p></> : null}</section>)}</div></div></section>
    <section className="section section--sand"><div className="section__inner"><SectionHeading title="Dietary Guidance" intro="We want your meal to be exceptional. Please share any severe allergies or dietary preferences with your server before ordering so we can accommodate you safely." /><div className="dietary-grid">{dietaryMarkers.map((marker) => <div key={marker.code}><strong>{marker.code}</strong><span>{marker.label}</span></div>)}<div><strong>MP</strong><span>Market Price</span></div></div><p className="meta">* Consuming raw or undercooked meats, poultry, seafood, shellfish, or eggs may increase your risk of foodborne illness.</p></div></section>
    <section className="section section--tight"><aside className="notice"><h2>Dinner changes with the season</h2><div><p>Items, ingredients, and prices may change as availability shifts. This page reflects our most recently published Dinner menu but may differ slightly from what is served during your visit.</p><p className="meta">Menu updated August 2026</p></div></aside></section>
    <section className="section section--navy"><div className="section__inner"><SectionHeading title="Join us for dinner" intro="Dinner is served Tuesday through Sunday in Charleston." centered light /><Actions centered><ButtonLink href="/visit#contact" variant="light">Reserve a Table</ButtonLink><ButtonLink href="/visit" variant="light">Plan Your Visit</ButtonLink><ButtonLink href="/menus" variant="light">Explore All Menus</ButtonLink></Actions></div></section>
  </>;
}
